### ISSUE TITLE
any idea in best way to integrate this sample with backend parse.com?

### ISSUE THREAD

**Issue by steve21124** [taskrabbit/ReactNativeSampleApp#10]

**Comment by bleonard** [comment]
I did a google and some things came up:
http://www.raywenderlich.com/106369/integrating-parse-react-native-ios
https://github.com/ParsePlatform/ParseReact

High level, you'll need to be able to write and read data -- the library should work for that.
In this sample app it should work if you switch out at library for the http client and the service layer.
For example, the [PostService](https://github.com/taskrabbit/ReactNativeSampleApp/blob/master/App/Api/PostService.js)
 which handles reading and writing those objects.

**Comment by steve21124** [comment]
Thanks, yeah agree. Service Layer is the best way to switch it to parse
