### ISSUE TITLE
Image has no propType 

### ISSUE THREAD

**Issue by dhunniecutt** [taskrabbit/ReactNativeSampleApp#16]
Hi,
Trying to run your sample. When I build in xcode I get the following error in the simulator: 
Image has no propType for native prop RCTImageView.defaultImageSrc of native UIImage.

Any idea what I may be missing?

**Comment by bleonard** [comment]
I don't believe we're even using an `ImageView` in this project.
Were you running the packager from another project? sometimes that is an issue.

**Comment by dhunniecutt** [comment]
Not running from another project. Opened the Sample.xcworkspace and followed the instructions under IOS and Server on the read me. Maybe I missed a step though? In the screenshot you can see where it is attempting to verify the prop.

<img width="1358" alt="screen shot 2016-01-07 at 11 31 00 pm" src="https://cloud.githubusercontent.com/assets/5632615/12190514/55c6e984-b597-11e5-9990-95043fe5213b.png">

**Comment by jrichardlai** [comment]
Is the packager running correctly? Can you close it and let the app run it and check there is no error ?

**Comment by dhunniecutt** [comment]
I'm pretty new to react-native, not sure what packager you're referring to?

**Comment by ronak301** [comment]
I had same problem. i checked and found , packager already running in terminal for other project. Closed it. Running fine now.

**Comment by bleonard** [comment]
I've found most problems are something like that with restarting the packager.
