### ISSUE TITLE
Cocoapods issue

### ISSUE THREAD

**Issue by jorilallo** [taskrabbit/ReactNativeSampleApp#4]
```
ld: library not found for -lSimulatorRemoteNotifications
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm running into this issue when compiling the project. Probably some simple Cocoapods issue but unfortunately I'm new to pods.

**Comment by bleonard** [comment]
maybe update cocoapods?

**Comment by JasonZ321** [comment]
my cocoapods version is 0.39.0, but I still get this error.
ld: library not found for -lSimulatorRemoteNotifications
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bleonard** [comment]
I assume that error is coming from XCode on compile.
Are you sure you are launching the xcworkspace and not the xcproject file?

This also suggests trying `pod update`
http://stackoverflow.com/questions/24050012/error-library-not-found-for

**Comment by JasonZ321** [comment]
Yes! should be xcworkspace. Thank you very much.
