### ISSUE TITLE
Login Alert: Server Error: 520

### ISSUE THREAD

**Issue by prakasa1904** [taskrabbit/ReactNativeSampleApp#41]
I found error when login : Login Alert: Server Error: 520

somebody knows how to fix that, I really don't know how to debug server

**Comment by bleonard** [comment]
make sure server is running
* Install nvm and node-4.2.3
* Install dependencies: `npm install`
* Run it: `npm start`

On android, you might also need to something like this
* You might need to do this to run it in Android Studio or on real device: `adb reverse tcp:8081 tcp:8081`
* And for the sample server: `adb reverse tcp:3000 tcp:3000`

Those and others in the readme.
help?

**Comment by prakasa1904** [comment]
sorry, it have been done... My bad, I miss something before hhee.. Thx for your response
